# Generated by Django 3.2.6 on 2021-08-27 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.category'),
        ),
    ]
