# Generated by Django 3.2.6 on 2021-08-31 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
