# Generated by Django 3.2.6 on 2021-08-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_user',
            field=models.CharField(max_length=64),
        ),
    ]
