# Generated by Django 3.2.6 on 2021-09-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auction_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
